version: 2

sources:
  - name: staging
    database: dtc-de-course-411615
    schema: trips_data_all

    tables:
      - name: green_tripdata
      - name: yellow_tripdata
      - name: fhv_tripdata